name: AWS Deploy Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 del api.server socket.server
          git clone git@github.com:marcodali/mirna-sockets.git
          export NODE_ENV=production
          cp .env ~/mirna-sockets/
          cd ~/mirna-sockets/
          yarn
          pm2 start servers/socket.server.js
          pm2 start servers/api.server.js
          pm2 save
          echo "hice deploy desde github-actions a las" `date` >> ~/log.txt
          cd ~/
          rm -rf ~/mirna-sockets/
