name: AWS Deploy Backend
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 del index
          rm -rf ~/mirna-sockets/
          git clone git@github.com:marcodali/mirna-sockets.git
          export NODE_ENV=production
          cd ~/mirna-sockets/
          yarn
          pm2 start index.js
          pm2 save
          pm2 show index
          echo "hice deploy desde github-actions a las" `date` >> ~/log.txt
