name: AWS Deploy Backend
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          whoami
          pwd
          cd /home/ubuntu/sockets-BE
          pm2 del index
          git pull
          rm -rf node_modules/
          yarn
          pm2 start index.js
          pm2 save
          echo "hice deploy desde github-actions a las" `date` >> ~/log.txt
